kdcokenny/opencode-notify:
  - source: workers/kdco-registry/files/plugin/notify.ts
    dest: src/notify.ts
  - source: facades/opencode-notify/README.md
    dest: README.md

kdcokenny/opencode-background-agents:
  - source: workers/kdco-registry/files/plugin/background-agents.ts
    dest: src/plugin/background-agents.ts
  - source: facades/opencode-background-agents/README.md
    dest: README.md

kdcokenny/opencode-worktree:
  - source: workers/kdco-registry/files/plugin/worktree-plugin.ts
    dest: src/plugin/worktree-plugin.ts
  - source: facades/opencode-worktree/README.md
    dest: README.md

kdcokenny/opencode-workspace:
  - source: workers/kdco-registry/files/plugin/workspace-plugin.ts
    dest: src/plugin/workspace-plugin.ts
  - source: facades/opencode-workspace/README.md
    dest: README.md
